// <auto-generated />
using System;
using LudoEngine.DbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LudoEngine.Migrations
{
    [DbContext(typeof(LudoContext))]
    [Migration("20210413074953_playerIntTypeAdded")]
    partial class playerIntTypeAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.2.21154.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LudoEngine.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("int");

                    b.Property<int?>("FirstPlace")
                        .HasColumnType("int");

                    b.Property<int?>("FourthPlace")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSaved")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlayerGameGameId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerGamePlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondPlace")
                        .HasColumnType("int");

                    b.Property<int?>("ThirdPlace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerGameGameId", "PlayerGamePlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("LudoEngine.Models.PawnSavePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerType")
                        .HasColumnType("int");

                    b.Property<int>("XPosition")
                        .HasColumnType("int");

                    b.Property<int>("YPosition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PawnSavePoints");
                });

            modelBuilder.Entity("LudoEngine.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlayerGameGameId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerGamePlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerGameGameId", "PlayerGamePlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LudoEngine.Models.PlayerGame", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("LudoEngine.Models.Game", b =>
                {
                    b.HasOne("LudoEngine.Models.PlayerGame", null)
                        .WithMany("Game")
                        .HasForeignKey("PlayerGameGameId", "PlayerGamePlayerId");
                });

            modelBuilder.Entity("LudoEngine.Models.Player", b =>
                {
                    b.HasOne("LudoEngine.Models.PlayerGame", null)
                        .WithMany("Player")
                        .HasForeignKey("PlayerGameGameId", "PlayerGamePlayerId");
                });

            modelBuilder.Entity("LudoEngine.Models.PlayerGame", b =>
                {
                    b.Navigation("Game");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
